version: '2'
services:
    kenyaemr2:
        container_name: kenyaemr2
        build: kenyaemr2
        depends_on:
            - kenyaemr2-mysql
        image: kenyaemr:latest
        env_file: main.env
        volumes:
             - ./openmrs:/root/.OpenMRS
        restart: unless-stopped
        ports:
            - 8089:8080
        networks:
            - ke_network
    kenyaemr2-mysql:
        build: mysql
        container_name: kenyaemr2-mysql
        env_file: main.env
        networks:
            - network
        volumes:
            - data2:/opt/kenyaemr/data
            - /var/lib/mysql
#        hostname: kenyaemr-mysql
        restart: unless-stopped
        ports: 
            - 3308:3306
        networks:
            - ke_network
networks:
    ke_network:
volumes:
    data2:
